const express=require('express')
const app=express()
app.use(express.json())
const apirouter=require('./router/api')
const mongoose=require('mongoose')
mongoose.connect('mongodb://127.0.0.1:27017/shopingcart')

app.use('/api',apirouter)
app.use(express.static('public'))
app.listen(5000,()=>{console.log("Server is running 5000 ")})